name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build with Maven
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Build with Maven
        run: |
          cd $GITHUB_WORKSPACE  # Navigate to the root of the repository
          chmod +x mvnw  # If using the Maven Wrapper
          ./mvnw clean install  # Replace with your Maven commands
